sudo: required
language: bash

services:
  - docker

env:
  matrix:
  - IMAGE_NAME=debian-systemd DOCKERFILE_PATH=systemd/debian/buster TAG=buster
  - IMAGE_NAME=debian-systemd DOCKERFILE_PATH=systemd/debian/stretch TAG=stretch
  - IMAGE_NAME=debian-systemd DOCKERFILE_PATH=systemd/debian/jessie TAG=jessie

script:
  - cd "$DOCKERFILE_PATH"
  - docker build . -t trly/"$IMAGE_NAME":"$TAG"

after_script:
  - docker images
