sudo: required
language: bash

services:
  - docker

env:
  matrix:
  - BASE_IMAGE=debian:buster IMAGE_NAME=debian-systemd TAG=buster
  - BASE_IMAGE=debian:buster-slim IMAGE_NAME=debian-systemd TAG=buster-slim
  - BASE_IMAGE=debian:stretch IMAGE_NAME=debian-systemd TAG=stretch
  - BASE_IMAGE=debian:stretch-slim IMAGE_NAME=debian-systemd TAG=stretch-slim
  - BASE_IMAGE=debian:jessie IMAGE_NAME=debian-systemd TAG=jessie
  - BASE_IMAGE=debian:jessie-slim IMAGE_NAME=debian-systemd TAG=jessie-slim

script:
  - docker build . -t trly/"$IMAGE_NAME":"$TAG" --build-arg base_image="$BASE_IMAGE"

after_script:
  - docker images
